In [1]:
import numpy as np
import statsmodels.api as sm   

# statsmodels.api offers classes and methods for fitting different types of regression models such 
# as Ordinary Least Squares (OLS), Generalized Linear Models (GLM), Logistic Regression, Poisson Regression, etc.

# here we use OLS model - ordinary least square to find p and r values

In [2]:
np.random.seed(42)

x = np.random.rand(100, 5)   # x with 5 features from 0,1
epsilon = np.random.normal(0,.5,100)    # error term

In [3]:
# equation of the plane

# y = b0 x1 + b1 x2 +.....+ bn xn + epsilon

y = 2*x[:,0] + 3*x[:,1] + 1.5*x[:,2] + 4*x[:,3]

In [4]:
y

array([7.09384801, 4.18996414, 5.04891895, 3.79445047, 3.54585172,
       5.3103832 , 5.61978161, 5.41407628, 5.41847159, 5.22712095,
       9.25312554, 2.58410943, 4.26152125, 3.00966289, 5.41076547,
       5.31675527, 4.34668167, 7.34437236, 5.76520922, 3.29877772,
       4.47790634, 3.7782526 , 5.69019476, 8.00402849, 5.22036712,
       4.62716427, 3.03140417, 4.71182458, 4.62962748, 2.86240044,
       4.71037079, 4.59349678, 5.72587706, 3.07582352, 3.0790149 ,
       6.74856905, 5.91895111, 6.72303822, 6.76088572, 7.77029727,
       5.37314301, 1.33830772, 5.0481723 , 5.16896597, 4.63152696,
       7.56484376, 5.93296049, 4.90558445, 7.59563429, 8.44565171,
       4.288584  , 7.24635622, 6.48362064, 6.06427519, 9.00263318,
       7.18073153, 3.73329834, 3.42881056, 2.84770847, 6.16976062,
       5.05809963, 7.16578469, 5.00193176, 3.5044969 , 5.35227275,
       5.73483736, 3.47136448, 5.60002146, 4.39885646, 4.70338762,
       5.2155202 , 6.00395683, 5.576051  , 5.79696747, 3.12991

In [5]:
x_with_intercept = sm.add_constant(x)   # there are no intercept so we have to add the intercept manually so it will add
# a cokumn of 1 thats its intercept

In [6]:
x_with_intercept

array([[1.        , 0.37454012, 0.95071431, 0.73199394, 0.59865848,
        0.15601864],
       [1.        , 0.15599452, 0.05808361, 0.86617615, 0.60111501,
        0.70807258],
       [1.        , 0.02058449, 0.96990985, 0.83244264, 0.21233911,
        0.18182497],
       [1.        , 0.18340451, 0.30424224, 0.52475643, 0.43194502,
        0.29122914],
       [1.        , 0.61185289, 0.13949386, 0.29214465, 0.36636184,
        0.45606998],
       [1.        , 0.78517596, 0.19967378, 0.51423444, 0.59241457,
        0.04645041],
       [1.        , 0.60754485, 0.17052412, 0.06505159, 0.94888554,
        0.96563203],
       [1.        , 0.80839735, 0.30461377, 0.09767211, 0.68423303,
        0.44015249],
       [1.        , 0.12203823, 0.49517691, 0.03438852, 0.9093204 ,
        0.25877998],
       [1.        , 0.66252228, 0.31171108, 0.52006802, 0.54671028,
        0.18485446],
       [1.        , 0.96958463, 0.77513282, 0.93949894, 0.89482735,
        0.59789998],
       [1.        , 0

In [7]:
model = sm.OLS(y, x_with_intercept).fit()

In [8]:
model.pvalues

array([0.72001959, 0.        , 0.        , 0.        , 0.        ,
       0.44035216])

In [9]:
model.rsquared

1.0

# backward elemination

In [18]:
# lets do backward elemination method

significant_level = .05     

while True:
    p_value = model.pvalues[1:]    # excluding intercepts pvalue
    max_pvalue = p_value.max()
    if max_pvalue > significant_level:
        max_index = np.argmax(p_value)    # finding the index
        x = np.delete(x, max_index, axis=1)
        x_with_intercept = sm.add_constant(x)
        model = sm.OLS(y, x_with_intercept).fit()
    else:
        break
        
print("final model")
print(model.summary())

final model
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.257e+31
Date:                Tue, 09 Jan 2024   Prob (F-statistic):               0.00
Time:                        14:42:59   Log-Likelihood:                 3283.4
No. Observations:                 100   AIC:                            -6557.
Df Residuals:                      95   BIC:                            -6544.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2.914e-15   5.37e-16     -5.

In [22]:
np.random.seed(42)
x = np.random.rand(100,5)
epsilon = np.random.normal(0, .5, 100)

y = 3*x[:,0] + 2*x[:,1] + 4*x[:,2] + 1.5*x[:,3] + epsilon

import statsmodels.api as sm

x_with_intercept = sm.add_constant(x)
model = sm.OLS(y, x_with_intercept).fit()

significant_level = .05

p_values = model.pvalues

while True:
    p_value = model.pvalues[1:]
    max_pvalue = p_value.max()
    if max_pvalue > significant_level:
        max_index = np.argmax(p_value)
        x = np.delete(x, max_index, axis=1)
        x_with_intercept = sm.add_constant(x)
        model = sm.OLS(y, x_with_intercept).fit()
    else:
        break

print(p_values)
print("\n")
print("final model ")
print(model.summary())

[6.08638171e-01 1.61621448e-26 2.09079259e-15 1.23759924e-38
 8.51724140e-12 3.99570939e-01]


final model 
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.886
Model:                            OLS   Adj. R-squared:                  0.882
Method:                 Least Squares   F-statistic:                     185.5
Date:                Tue, 09 Jan 2024   Prob (F-statistic):           5.60e-44
Time:                        14:54:42   Log-Likelihood:                -78.795
No. Observations:                 100   AIC:                             167.6
Df Residuals:                      95   BIC:                             180.6
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------

In [ ]:
import statsmodels.formula.api as sm
def backwardElimination(x, SL):
    numVars = len(x[0])
    temp = np.zeros((21613,19)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    temp[:,j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x).fit()
                    adjR_after = tmp_regressor.rsquared_adj.astype(float)
                    if (adjR_before >= adjR_after):
                        x_rollback = np.hstack((x, temp[:,[0,j]]))
                        x_rollback = np.delete(x_rollback, j, 1)
                        print (regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    regressor_OLS.summary()
    return x


SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17]]
X_Modeled = backwardElimination(X_opt, SL)