# Implementation of Python Basic Libraries such as Statistics, Math, Numpy and Scipy

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Usage of methods such as floor(), ceil(), sqrt(), isqrt(), gcd() etc. 

In [6]:
import math
a = 5.567
math.floor(a)

5

In [8]:
math.ceil(a)

6

In [9]:
math.sqrt(a)

2.3594490882407273

In [11]:
b = 6
math.isqrt(6)

2

In [19]:
math.gcd(24,21)

3

In [18]:
math.lcm(24, 1122)

4488

# Usage of attributes of array such as ndim, shape, size, methods such as sum(), mean(), sort(), sin() etc. 

In [20]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
np.ndim(a)

1

In [31]:
a = np.array([[8,2,5,4],[1,6,2,8]])

np.ndim(a)

2

In [24]:
np.shape(a)

(2, 4)

In [25]:
np.size(a)

8

In [26]:
b = np.array([[1,2,3,4],[5,6,7,8]])
c = a + b
c

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [29]:
np.mean(a)

4.5

In [32]:
print(a)
np.sort(a)

[[8 2 5 4]
 [1 6 2 8]]


array([[2, 4, 5, 8],
       [1, 2, 6, 8]])

In [33]:
np.sin(a)

array([[ 0.98935825,  0.90929743, -0.95892427, -0.7568025 ],
       [ 0.84147098, -0.2794155 ,  0.90929743,  0.98935825]])

# Usage of methods such as det(), eig() etc. 

In [37]:
b = np.array([[1,2],[4,5]])

In [41]:
print( "determinent of matrix a = ",np.linalg.det(b))

determinent of matrix a =  -2.9999999999999996


In [43]:
print( "determinent of matrix a = ","\n",np.linalg.eig(b))

determinent of matrix a =  
 EigResult(eigenvalues=array([-0.46410162,  6.46410162]), eigenvectors=array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))


In [44]:
np.linalg.inv(b)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

# Consider a list datatype (1D) then reshape it into 2D, 3D matrix using numpy 

In [47]:
a = np.array([1,2,3,4])
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [46]:
b = np.array([[1,2,3],[5,6,7]])
b.reshape((3,2))

array([[1, 2],
       [3, 5],
       [6, 7]])

In [48]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Generate random matrices using numpy 

In [50]:
a = np.random.rand(3,3)
a

array([[0.25168054, 0.29368845, 0.56897372],
       [0.00169959, 0.46885257, 0.84565083],
       [0.77435034, 0.97516802, 0.9503967 ]])

In [55]:
b = np.random.rand(2,4)
b

array([[0.86438104, 0.84990676, 0.64596521, 0.45685949],
       [0.24001531, 0.18331787, 0.39646816, 0.75726485]])

# Generate random matrices using numpy 

In [56]:
from scipy.linalg import det

deter = det(a)

In [57]:
deter

-0.10918572406805407

In [60]:
from scipy.linalg import eig

eigen_val, eig_vector = eig(a)

print(f"eigen values : {eigen_val} \n ")
print(f"eigen vector : {eig_vector}")


eigen values : [ 1.88572335+0.j  0.15610903+0.j -0.37090257+0.j] 
 
eigen vector : [[-0.36423215 -0.63754484 -0.29580478]
 [-0.47761915  0.72299811 -0.677524  ]
 [-0.79950915 -0.26610205  0.67339496]]
