In [44]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import pandas as pd 

%matplotlib inline

In [45]:
df = pd.read_csv("./indeed_job_data.csv")
df.head()

Title                     Company Location  \
0    PO, Research & Data Analyst        The Elevation Church  Nigeria   
1             QA Tester - Intern             mDoc Healthcare    Lagos   
2      Data Analyst - Healthcare                 eMedicStore    Lagos   
3                     HR Analyst  Jobrole Consulting Limited    Ikeja   
4  Business Intelligence Analyst       TSL Metroline Limited    Lagos   

                        Salary   Job Type                Date Posted  \
0                          NaN  Full-time          PostedJust posted   
1                          NaN        NaN  EmployerActive 6 days ago   
2                          NaN        NaN  EmployerActive 5 days ago   
3  ₦150,000 - ₦200,000 a month  Full-time    PostedPosted 2 days ago   
4                          NaN        NaN     PostedPosted 1 day ago   

                                             Summary  
0  Train volunteers on the use of M&E frameworks ...  
1  Advanced knowledge of data security and encryp...  
2  Implement new data analysis methodologies and ...  
3  Analyze and interpret data to generate actiona...  
4  Analyse business information/ data to identify...

In [46]:
df.shape

(203, 7)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Title        203 non-null    object
 1   Company      200 non-null    object
 2   Location     203 non-null    object
 3   Salary       15 non-null     object
 4   Job Type     101 non-null    object
 5   Date Posted  203 non-null    object
 6   Summary      203 non-null    object
dtypes: object(7)
memory usage: 11.2+ KB


null values are there 

In [48]:
df.isnull().sum()

Title            0
Company          3
Location         0
Salary         188
Job Type       102
Date Posted      0
Summary          0
dtype: int64

In [49]:
df['Company'].fillna("unknown", inplace= True)
df['Job Type'].fillna("unknown", inplace = True)

In [50]:
df['Salary'].unique()

array([nan, '₦150,000 - ₦200,000 a month', '₦100,000 - ₦150,000 a month',
       '₦200,000 a month', '₦70,000 - ₦150,000 a month',
       '₦90,000 - ₦130,000 a month', '₦300,000 - ₦350,000 a month',
       '₦450,000 - ₦600,000 a month', '₦200,000 - ₦250,000 a month',
       '₦220,000 a month', '₦60,000 - ₦80,000 a month'], dtype=object)

In [51]:
df['Salary'] = df['Salary'].str.replace('[₦,a-zA-Z\s]','',regex = True)
df['Salary'].unique()

array([nan, '150000-200000', '100000-150000', '200000', '70000-150000',
       '90000-130000', '300000-350000', '450000-600000', '200000-250000',
       '220000', '60000-80000'], dtype=object)

In [52]:
a = '5-6'
def type_covert(a):
    if isinstance(a, str) and '-' in a:
        lower, upper = map(int, a.split('-'))
        return (lower+upper)/2
    else :
        return a
a = type_covert(a)
a

5.5

In [53]:
def salary_convert(salary):
    if isinstance(salary, str) and '-' in salary:
        lower, upper = map(int, salary.split('-'))
        return (upper + lower)/2
    else:
        return salary

df['Salary'] = df['Salary'].apply(salary_convert)

In [54]:
df['Salary'] = df['Salary'].astype(float)
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df['Salary'].unique()

array([175000., 125000., 200000., 110000., 325000., 525000., 225000.,
       220000.,  70000.])

In [55]:
df.isnull().sum()

Title          0
Company        0
Location       0
Salary         0
Job Type       0
Date Posted    0
Summary        0
dtype: int64

In [56]:
df['Job Type'].unique()

array(['Full-time', 'unknown', 'Temporary', 'Full-time +1', 'Contract',
       'Permanent'], dtype=object)

In [57]:
df['Job Type'] = df['Job Type'].replace({'Full-time' : 'Fulltime', 'Full-time +1' : 'Fulltime'})
df['Job Type'].unique()

array(['Fulltime', 'unknown', 'Temporary', 'Contract', 'Permanent'],
      dtype=object)

# parse date

In [58]:
df['Date Posted'].unique()

array(['PostedJust posted', 'EmployerActive 6 days ago',
       'EmployerActive 5 days ago', 'PostedPosted 2 days ago',
       'PostedPosted 1 day ago', 'PostedPosted 6 days ago',
       'PostedPosted 30+ days ago', 'PostedPosted 26 days ago',
       'PostedPosted 12 days ago', 'EmployerActive 24 days ago',
       'EmployerActive 7 days ago', 'PostedPosted 7 days ago',
       'EmployerActive 19 days ago', 'PostedPosted 18 days ago',
       'PostedPosted 25 days ago', 'PostedPosted 13 days ago',
       'PostedPosted 19 days ago', 'PostedPosted 20 days ago',
       'PostedPosted 8 days ago', 'PostedPosted 14 days ago',
       'PostedPosted 11 days ago', 'PostedPosted 4 days ago',
       'PostedToday', 'PostedPosted 29 days ago',
       'EmployerActive 20 days ago', 'PostedPosted 28 days ago',
       'PostedPosted 10 days ago', 'PostedPosted 21 days ago',
       'PostedPosted 27 days ago', 'EmployerActive 15 days ago',
       'PostedPosted 15 days ago', 'PostedPosted 3 days ago',
       '

In [59]:
df['Date Posted'] = df['Date Posted'].str.replace("Posted","")
df['Date Posted'] =df['Date Posted'].str.replace("EmployerActive","")
df['Date Posted'].unique()

array(['Just posted', ' 6 days ago', ' 5 days ago', ' 2 days ago',
       ' 1 day ago', ' 30+ days ago', ' 26 days ago', ' 12 days ago',
       ' 24 days ago', ' 7 days ago', ' 19 days ago', ' 18 days ago',
       ' 25 days ago', ' 13 days ago', ' 20 days ago', ' 8 days ago',
       ' 14 days ago', ' 11 days ago', ' 4 days ago', 'Today',
       ' 29 days ago', ' 28 days ago', ' 10 days ago', ' 21 days ago',
       ' 27 days ago', ' 15 days ago', ' 3 days ago', ' 9 days ago',
       ' 16 days ago', ' 22 days ago'], dtype=object)

In [60]:
df['Date Posted'] = df['Date Posted'].str.replace('Today', '0 days ago')  # Replace "Today" with "0 days ago"
df['Date Posted'] = df['Date Posted'].str.replace('PostedJust ', '0 days ago')  # Replace "PostedJust " with "0 days ago"
df['Date Posted'] = df['Date Posted'].str.replace('postedPosted', '')  # Remove "postedposted"
df['Date Posted'] = df['Date Posted'].str.replace('Just posted', '0 days ago')

In [61]:
df['Date Posted'] = df['Date Posted'].str.replace('PostedPosted', '')
df['Date Posted'] = df['Date Posted'].str.replace("Posted","")

In [62]:
df['Date Posted'].unique()

array(['0 days ago', ' 6 days ago', ' 5 days ago', ' 2 days ago',
       ' 1 day ago', ' 30+ days ago', ' 26 days ago', ' 12 days ago',
       ' 24 days ago', ' 7 days ago', ' 19 days ago', ' 18 days ago',
       ' 25 days ago', ' 13 days ago', ' 20 days ago', ' 8 days ago',
       ' 14 days ago', ' 11 days ago', ' 4 days ago', ' 29 days ago',
       ' 28 days ago', ' 10 days ago', ' 21 days ago', ' 27 days ago',
       ' 15 days ago', ' 3 days ago', ' 9 days ago', ' 16 days ago',
       ' 22 days ago'], dtype=object)

In [63]:
import pandas as pd

# Get the current date and time
current_timestamp = pd.Timestamp.now()
print("Current Timestamp:", current_timestamp)

# Normalize the timestamp to midnight of the same date
normalized_timestamp = current_timestamp.normalize()
print("Normalized Timestamp:", normalized_timestamp)


Current Timestamp: 2024-05-25 11:37:45.654574
Normalized Timestamp: 2024-05-25 00:00:00


In [64]:
def date_parse(date):
    if '+' in date:
        return pd.Timestamp.now().normalize() - pd.Timedelta(days = 30)
    else:
        return pd.Timestamp.now().normalize() - pd.Timedelta(days = int(date.split()[0]))

In [65]:
df['Date Posted'] = df['Date Posted'].apply(date_parse)

In [66]:
df['Date Posted'].unique()

array(['2024-05-25T00:00:00.000000000', '2024-05-19T00:00:00.000000000',
       '2024-05-20T00:00:00.000000000', '2024-05-23T00:00:00.000000000',
       '2024-05-24T00:00:00.000000000', '2024-04-25T00:00:00.000000000',
       '2024-04-29T00:00:00.000000000', '2024-05-13T00:00:00.000000000',
       '2024-05-01T00:00:00.000000000', '2024-05-18T00:00:00.000000000',
       '2024-05-06T00:00:00.000000000', '2024-05-07T00:00:00.000000000',
       '2024-04-30T00:00:00.000000000', '2024-05-12T00:00:00.000000000',
       '2024-05-05T00:00:00.000000000', '2024-05-17T00:00:00.000000000',
       '2024-05-11T00:00:00.000000000', '2024-05-14T00:00:00.000000000',
       '2024-05-21T00:00:00.000000000', '2024-04-26T00:00:00.000000000',
       '2024-04-27T00:00:00.000000000', '2024-05-15T00:00:00.000000000',
       '2024-05-04T00:00:00.000000000', '2024-04-28T00:00:00.000000000',
       '2024-05-10T00:00:00.000000000', '2024-05-22T00:00:00.000000000',
       '2024-05-16T00:00:00.000000000', '2024-05-09

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Title        203 non-null    object        
 1   Company      203 non-null    object        
 2   Location     203 non-null    object        
 3   Salary       203 non-null    float64       
 4   Job Type     203 non-null    object        
 5   Date Posted  203 non-null    datetime64[ns]
 6   Summary      203 non-null    object        
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 11.2+ KB


In [68]:
a = df['Summary'].sample().tolist()
a

['Minimum of 3 years working experience as a data analyst or business data analyst.\nAcquire data from primary or secondary data sources and maintain databases…']

In [69]:
import re

def clean_summary(data):
    if not isinstance(data, str):
        data = str(data)
    clean_data = re.sub("[^a-zA-Z\s,.!?]", "", data)
    clean_data = " ".join(clean_data.split())
    return clean_data
    
df['Summary'] = df['Summary'].apply(clean_summary)

In [70]:
a = df['Summary'].sample().tolist()
a

['Business Analysis Instructor Nigeria Remote. The Business Analysis School was founded by Eno Eka, an accountant who successfully transitioned into Business']

# EDA

# Visualisation

In [71]:
df.head()

Title                     Company Location  \
0    PO, Research & Data Analyst        The Elevation Church  Nigeria   
1             QA Tester - Intern             mDoc Healthcare    Lagos   
2      Data Analyst - Healthcare                 eMedicStore    Lagos   
3                     HR Analyst  Jobrole Consulting Limited    Ikeja   
4  Business Intelligence Analyst       TSL Metroline Limited    Lagos   

     Salary  Job Type Date Posted  \
0  175000.0  Fulltime  2024-05-25   
1  175000.0   unknown  2024-05-19   
2  175000.0   unknown  2024-05-20   
3  175000.0  Fulltime  2024-05-23   
4  175000.0   unknown  2024-05-24   

                                             Summary  
0  Train volunteers on the use of ME frameworks a...  
1  Advanced knowledge of data security and encryp...  
2  Implement new data analysis methodologies and ...  
3  Analyze and interpret data to generate actiona...  
4  Analyse business information data to identify ...

In [73]:
df['Location'].unique()

array(['Nigeria', 'Lagos', 'Ikeja', 'Shagamu', 'Abuja', 'Sokoto',
       'Zamfara', 'Abeokuta', 'Cross River', 'Yaba', 'Gombe', 'Plateau',
       'Ibadan', 'Kebbi', 'Oyo', 'Ogun', 'Benin City', 'Osogbo'],
      dtype=object)