# exam - 24/11/23

In [29]:
import numpy as np

In [3]:
# 1.
a = 3.1456789
round(a,3)

3.146

In [4]:
# 2
a = input("enter the 1st input string :")
b = input("enter the 2nd input string :")
c = input("enter the 3rd input string :")

enter the 1st input string :amal
enter the 2nd input string :fadhil
enter the 3rd input string :harshit


In [5]:
print(a,b,c)

amal fadhil harshit


In [8]:
# 3
a = [1,2,3,4]
for i in a:
    print(i**2)

1
4
9
16


In [12]:
# 4
a = [1,2,3,4]
b = [5,6,7,8]
for i,j in zip(a,b):
    print(a,b[::-1])
    break

[1, 2, 3, 4] [8, 7, 6, 5]


In [15]:
5#
a = int(input("enter the number :"))
print(f"{a} + 1 = ",a+1)

enter the number :5
5 + 1 =  6


In [ ]:
# 6
a = [4, "a", [1,2], 4]
a[::-1]



In [94]:
# 7 
for i in range(1,5):
    for j in reversed(range(i,6)):
        print(j, end="")
    print()

54321
5432
543
54


In [3]:
# 8

a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for i in a:
    if i % 2 ==0:
        print(i)

2
4
6
8
10
12
14
16
18
20


In [86]:
# 9
for i in range(4):
    print("*"*i)
for j in reversed(range(3)):
    print("*"*j)



*
**
***
**
*



In [119]:
# 10

a = [1,2,3,4,5]
n = 3
while(i<len(a)):
    if i == n:
        a.pop(i)
    print(i)
    i+=1      
    

1
2
3


In [91]:
# 11
a = [1,2,3,4]
b = [5,6,7,8]
c = {}

for i, j in zip(a,b):
    c.


IndentationError: expected an indented block (3435537135.py, line 7)

In [11]:
# 12
a  = {"amal":1, "fadhi" :2, "kishor":3}
for i in a.keys:
    print(i)

TypeError: 'builtin_function_or_method' object is not iterable

In [112]:
# 13

a = (1,2,3,4)
b = a[0]
c = a[1]
d = a[2]
e = a[3]
print(a,b,c,d,e)

(1, 2, 3, 4) 1 2 3 4


In [18]:
# 14
a = (10,12,24,12,20)
a[1:3]
b = a[1:3]
b

(12, 24)

In [27]:
# 15

a = (('a',2),('b',0),('c',1))
for i in range(len(a)):
    for j in 
    

TypeError: 'builtin_function_or_method' object is not subscriptable

In [122]:
# 16

a = [1, 2, 3, 4, 2, 5, 6, 3]

set_a = set(a)

if len(a) != len(a):
    print("Duplicates ")
else:
    print("No duplicates ")


No duplicates 


In [34]:
# 17

a = np.arange(200,300,10).reshape(5,2)
a

array([[200, 210],
       [220, 230],
       [240, 250],
       [260, 270],
       [280, 290]])

In [53]:
# 18
a = np.array([[0,2,-1],[5,4,6],[7,8,5]])
a

print("axis 0")
print(a[0:1,:])

print("axis1")
print(a[:,0:1])  # axis 1

axis 0
[[ 0  2 -1]]
axis1
[[0]
 [5]
 [7]]


In [65]:
# 19

a = np.arange(8).reshape(4,2)
print(a)
print(a[1,1])
print(a[0,1])
print(a[0,0])


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
3
1
0


In [80]:
# 20
b = np.ones((3,3))
a = np.arange(9).reshape(3,3)
a[:,1:2] = b [:,1:2]
a

array([[0, 1, 2],
       [3, 1, 5],
       [6, 1, 8]])