In [ ]:

# write a function to write sum, div, mul 


def math_operator(a,b):
    print("product = ", a*b)
    print("sum = ", a+b)
    if(b == 0):
        print("dinominator cannot be zero ")
    else:    
        print("div = ", a/b)
    print("substraction = ", a-b)

math_operator(0,0)

In [ ]:
a = "maM"
b = a[::-1]

if a == b :
    print("a is equal to b ")
else :
    print( " a is not equal ")

# numpy

In [4]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.reshape(2,5)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
b = np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
a@b

array([[120, 130, 140, 150],
       [320, 355, 390, 425]])

In [10]:
np.dot(a,b)

array([[120, 130, 140, 150],
       [320, 355, 390, 425]])

In [16]:
c = np.array([[2,3,4,5],[1,2,3,4]])
c

array([[2, 3, 4, 5],
       [1, 2, 3, 4]])

In [11]:
a = np.array([[2,3,4,5],[1,2,3,4]])
b = np.array([[5,6,],[4,5],[6,7],[10,6]])
a@b

array([[96, 85],
       [71, 61]])

In [24]:
a = np.arange(20).reshape(5,4)
b= np.arange(20,40).reshape(5,4)
a+b

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [25]:
a-b

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [26]:
a*b

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [27]:
a/b

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [28]:
a = np.identity(5)

In [29]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
b = np.eye(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
b[3,3] = 5
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# b = np.diag()

In [39]:
np.matrix([[2],[2]])

matrix([[2],
        [2]])

In [41]:
b.size

25

In [42]:
# HTTP://DOCS

In [43]:
a = np.array([1,2,3,4])

In [44]:
a

array([1, 2, 3, 4])

In [45]:
a.size

4

In [46]:
a.dtype

dtype('int32')

In [47]:
a = np.append(a,5)

In [48]:
a

array([1, 2, 3, 4, 5])

In [52]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [55]:
# repertation
a = np.tile(5,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [56]:
x = np.arange(-1,1,.1)
print(x)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


## linespace and log space

In [58]:
np.logspace(0,np.e**2,10,base=np.e**2)

array([1.00000000e+00, 5.16555456e+00, 2.66829540e+01, 1.37832255e+02,
       7.11980032e+02, 3.67777170e+03, 1.89977304e+04, 9.81338130e+04,
       5.06915566e+05, 2.61850001e+06])

In [59]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [60]:
np.diag([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [61]:
np.diag([1,2,3,4],k=2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [62]:
a=np.diag([1,2,3,4],k=2).sum()

In [63]:
a

10

In [64]:
np.trace(np.diag([1,2,3,4]))

10

# slising

In [68]:
m = np.random.rand(10,2)
m

array([[0.28222514, 0.36210618],
       [0.0181575 , 0.49400154],
       [0.741207  , 0.03168215],
       [0.10030155, 0.75737899],
       [0.23576895, 0.80631305],
       [0.18217177, 0.04082307],
       [0.84663645, 0.75054461],
       [0.07728445, 0.26554286],
       [0.14534675, 0.39617179],
       [0.52030409, 0.5660631 ]])

In [69]:
m = np.random.rand(15,2)
m

array([[0.84100517, 0.9340207 ],
       [0.24516945, 0.06558337],
       [0.87309683, 0.91146158],
       [0.46701841, 0.50625924],
       [0.04414689, 0.214632  ],
       [0.29559204, 0.59673801],
       [0.80695489, 0.48300653],
       [0.88605326, 0.64596895],
       [0.59593089, 0.08319692],
       [0.32379096, 0.31621642],
       [0.93733404, 0.22749247],
       [0.92571721, 0.99318079],
       [0.9489171 , 0.22941774],
       [0.42479156, 0.7123787 ],
       [0.8281105 , 0.02534337]])

In [72]:
m = np.arange(10).reshape(5,2)

In [73]:
m

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
m[1,1]

3

In [76]:
m[1]

array([2, 3])

In [77]:
m[1,:]

array([2, 3])

In [79]:
m[0:3,:]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [82]:
m[:3]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [83]:
m[::-1]

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])